### ISSUE TITLE
TODO grand robot pour concours!

### ISSUE THREAD

**Issue by charlesvdv** [Ecam-Eurobot-2017/main#17]
## Mécanique
- [ ] funny action
- [x] finir pince 
- [ ] attacher la batterie
- [x] modifier le belier + ajouter calle
- [x] tester angle servo
- [x] checker pente toboggan/pince
- [ ] finiolage
- [x] fixer les US
- [x] besoin d'une calle ?

## Code
- [ ] régul
- [ ] path finding
- [ ] gerer les actions haut level (@SylvainAlonso tu seras mettre à jour ton code?)
- [ ] gerer les obstacles dynamiques
- [ ] gerer le start (@SylvainAlonso)
- [ ] mettre tout ensemble
